name: Build KernelSU Vili
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison ccache libncurses-dev libssl-dev xz-utils liblz4-tool git

      - name: Download Kernel Source & Toolchain
        run: |
          git clone --depth=1 -b vili-r-oss https://github.com/MiCode/Xiaomi_Kernel_OpenSource kernel
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang
          
      - name: Integrate KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Compile Kernel
        run: |
          export PATH=$(pwd)/clang/clang-stable/bin:$PATH
          cd kernel
          CONF=$(find arch/arm64/configs/ -name "*vili*" | head -n 1 | sed 's|arch/arm64/configs/||')
          make O=out ARCH=arm64 $CONF
          make O=out ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- -j$(nproc)

      - name: Upload Finished Boot Image
        uses: actions/upload-artifact@v4
        with:
          name: KernelSU_Boot_Vili
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
